/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AwCol {
    }
    interface AwComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface AwGrid {
    }
    interface AwRow {
    }
}
declare global {
    interface HTMLAwColElement extends Components.AwCol, HTMLStencilElement {
    }
    var HTMLAwColElement: {
        prototype: HTMLAwColElement;
        new (): HTMLAwColElement;
    };
    interface HTMLAwComponentElement extends Components.AwComponent, HTMLStencilElement {
    }
    var HTMLAwComponentElement: {
        prototype: HTMLAwComponentElement;
        new (): HTMLAwComponentElement;
    };
    interface HTMLAwGridElement extends Components.AwGrid, HTMLStencilElement {
    }
    var HTMLAwGridElement: {
        prototype: HTMLAwGridElement;
        new (): HTMLAwGridElement;
    };
    interface HTMLAwRowElement extends Components.AwRow, HTMLStencilElement {
    }
    var HTMLAwRowElement: {
        prototype: HTMLAwRowElement;
        new (): HTMLAwRowElement;
    };
    interface HTMLElementTagNameMap {
        "aw-col": HTMLAwColElement;
        "aw-component": HTMLAwComponentElement;
        "aw-grid": HTMLAwGridElement;
        "aw-row": HTMLAwRowElement;
    }
}
declare namespace LocalJSX {
    interface AwCol {
    }
    interface AwComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface AwGrid {
    }
    interface AwRow {
    }
    interface IntrinsicElements {
        "aw-col": AwCol;
        "aw-component": AwComponent;
        "aw-grid": AwGrid;
        "aw-row": AwRow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aw-col": LocalJSX.AwCol & JSXBase.HTMLAttributes<HTMLAwColElement>;
            "aw-component": LocalJSX.AwComponent & JSXBase.HTMLAttributes<HTMLAwComponentElement>;
            "aw-grid": LocalJSX.AwGrid & JSXBase.HTMLAttributes<HTMLAwGridElement>;
            "aw-row": LocalJSX.AwRow & JSXBase.HTMLAttributes<HTMLAwRowElement>;
        }
    }
}
